POST http://localhost:4000/customer/reservations/64b07c0a6b9feeae0e6501f1
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGIxYjBmNmVmMTc2ZTYwM2U1NGNlYWQiLCJuYW1lIjoiY2FpIiwiZW1haWwiOiJjYWlAYS5lZHUiLCJyb2xlIjoiY3VzdG9tZXIiLCJpYXQiOjE2ODkzNjY5MDV9.XaU-K1En3WXLjITM8fBmFWapHmQc7sf3hmV2dDvZNk4
Content-Type: application/json

{
  "name": "cai",
  "email": "cai@a.edu"
}

###
GET http://localhost:4000/customer/reservations/?page=1&page_size=10
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGIwNzU2MzRlMmY0Mjc4MDU3YTA4ODEiLCJuYW1lIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGFkbWluLmVkdSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY4OTI4NzY1OX0.DmrgZEESlu3C1yf-c4-gici7NgmG_jtOYZYZxY9ATkU
Accept: application/json

###
DELETE http://localhost:4000/customer/reservations/64b1aa6b994622381d8a368e
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGIxYjBmNmVmMTc2ZTYwM2U1NGNlYWQiLCJuYW1lIjoiY2FpIiwiZW1haWwiOiJjYWlAYS5lZHUiLCJyb2xlIjoiY3VzdG9tZXIiLCJpYXQiOjE2ODkzNjY5MDV9.XaU-K1En3WXLjITM8fBmFWapHmQc7sf3hmV2dDvZNk4
Content-Type: application/json
